name: manage-azure-policy-15f52bee
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Preview_Configure_supported_Windows_Arc_machines_to_automatically_install_the_Azure_Security_agent_d01f3018-de9f-4d75-8dae-d12c1875da9f/**'
#      - .github/workflows/manage-azure-policy-15f52bee.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_15f52bee}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Preview_Configure_supported_Windows_Arc_machines_to_automatically_install_the_Azure_Security_agent_d01f3018-de9f-4d75-8dae-d12c1875da9f/**
