name: manage-azure-policy-ed258133
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Preview_Configure_supported_Linux_virtual_machines_to_automatically_install_the_Azure_Security_agent_5f8eb305-9c9f-4abe-9bb0-df220d9faba2/**'
#      - .github/workflows/manage-azure-policy-ed258133.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ed258133}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Preview_Configure_supported_Linux_virtual_machines_to_automatically_install_the_Azure_Security_agent_5f8eb305-9c9f-4abe-9bb0-df220d9faba2/**
